// components/dashboard/TodaysBrief.tsx
import React from "react";

type AlertItem = {
  id: string;
  title: string;
  detail: string;
  severity: "info" | "warning" | "critical";
};

export type TodaysBriefProps = {
  alerts?: AlertItem[];
};

const fallbackAlerts: AlertItem[] = [
  {
    id: "a1",
    title: "GP risk – EL&N Oxford Circus",
    detail: "GP forecast 4.2% below target if current labour pattern continues.",
    severity: "warning",
  },
  {
    id: "a2",
    title: "Supplier price spike",
    detail: "Brakes dairy +6.9% vs 4-week average. Consider alternative supplier.",
    severity: "critical",
  },
  {
    id: "a3",
    title: "Review surge – Deliveroo",
    detail: "18 new reviews in the last 24h across Hyde Park kiosks.",
    severity: "info",
  },
];

export default function TodaysBrief({ alerts = fallbackAlerts }: TodaysBriefProps) {
  return (
    <section className="rounded-3xl border border-slate-800 bg-slate-950/95 p-4 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <div>
          <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">
            Today&apos;s brief
          </p>
          <p className="text-xs text-slate-300">
            Snapshot of what deserves your attention in the next 12 hours.
          </p>
        </div>
        <span className="rounded-full bg-sky-500/10 px-2 py-1 text-[10px] font-medium text-sky-300">
          Auto-generated by ODYAN
        </span>
      </div>

      <ul className="space-y-2 text-xs">
        {alerts.map((alert) => (
          <li
            key={alert.id}
            className="rounded-2xl border border-slate-800/80 bg-slate-900/80 px-3 py-2 flex gap-2"
          >
            <span
              className={
                "mt-0.5 h-2 w-2 rounded-full " +
                (alert.severity === "critical"
                  ? "bg-rose-400"
                  : alert.severity === "warning"
                  ? "bg-amber-400"
                  : "bg-sky-400")
              }
            />
            <div>
              <p className="font-medium text-slate-100">{alert.title}</p>
              <p className="text-[11px] text-slate-400">{alert.detail}</p>
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
